### ISSUE TITLE
Loaded session has expired

### ISSUE THREAD

**Issue by phong-diagon1** [wiverson/supabase-unity-template#5]
I am using Supabase cloud hosted, every time I have logged in and restart application (IOS, Android and Editor) the session from local storage was loaded in few second then `Loaded session has expired` has appeared

![image](https://github.com/wiverson/supabase-unity-template/assets/118701529/508ad314-f03e-4444-ac1e-1675d4b6e496)

I think because this line of code, line 85 in `SupabaseManager.cs` 
`await client.InitializeAsync();` 

I stucked with this error in 3 weeks and still not fix this, did I miss anything? 
Thank you

**Comment by wiverson** [comment]
I don't know, haven't really used this / touched this since the project was updated as TBH I moved over my personal stuff to Godot lately - this was a personal project.

Which version of Unity are you using?

**Comment by phong-diagon1** [comment]
I'm using Unity 2022.3.16, I tested on both Windows 11 & Mac OS Silicon

**Comment by gaetandezeiraud** [comment]
I can confirm, same here on Unity 6 Preview.

**Comment by gaetandezeiraud** [comment]
Ok, easy fix, just update Supabase Nuget packages. Manually or with https://github.com/GlitchEnzo/NuGetForUnity 
Fix some code errors (nothing complicated) and replace ` await client.InitializeAsync();` with `await client.RetrieveSessionAsync();`.

To help you, you now have to initialize the Client with the following code:
```csharp
Client client = new Supabase.Gotrue.Client(new ClientOptions
{
    AutoRefreshToken = true,
    Url = SupabaseSettings.SupabaseURL + "/auth/v1",
	Headers = new Dictionary<string, string>
	{
		{ "apikey", SupabaseSettings.SupabaseAnonKey }
	}
});
```

**Comment by phong-diagon1** [comment]
> Ok, easy fix, just update Supabase Nuget packages. Manually or with https://github.com/GlitchEnzo/NuGetForUnity Fix some code errors (nothing complicated) and replace ` await client.InitializeAsync();` with `await client.RetrieveSessionAsync();`.
> 
> To help you, you now have to initialize the Client with the following code:
> 
> ```cs
> Client client = new Supabase.Gotrue.Client(new ClientOptions
> {
>     AutoRefreshToken = true,
>     Url = SupabaseSettings.SupabaseURL + "/auth/v1",
> 	Headers = new Dictionary<string, string>
> 	{
> 		{ "apikey", SupabaseSettings.SupabaseAnonKey }
> 	}
> });
> ```

This helped me as well, thank you!
